### ISSUE TITLE
swiper-wrapper and bootstrap 4

### ISSUE THREAD

**Issue by alfupe** [JayChase/angular2-useful-swiper#27]
Hi there,

This is not an issue but an advice for those using bootstrap 4 (maybe 3?) and this module. If you don't want to go crazy until you discover it please create a simple css rule:
```css
.swiper-wrapper {
    box-sizing: border-box;
}
```
Otherwise your columns won't fit in the row as you are probably waiting for.
